controllers:
    host: 'symf.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.symf.fr'
    path: /login_check
    methods: [POST]

api_controller:
    host: 'api.symf.fr'
    resource: ../../src/ApiController/
    type: annotation